resources:
- name: liberator-repo
  type: git
  icon: github
  source:
    private_key: ((concourse-github.private_key))
    uri: git@github.com:Simspace/liberator.git
    branch: LB-330-bg-tasks-service
- name: python-base-image
  type: registry-image
  icon: docker
  source:
    username: ((concourse-dockerhub.username))
    password: ((concourse-dockerhub.password))
    repository: simspace/ac-python
    tag: 2.0.0
- name: ac-loguru-repo
  type: git
  icon: github
  source:
    private_key: ((concourse-github.private_key))
    uri: git@github.com:SimSpace-RT/ac-common.git
    branch: ac_loguru-v2.1.2

jobs:
- name: integration
  plan:

  - get: liberator-repo
  - get: ac-loguru-repo
  - get: python-base-image
    params:
      format: oci

  - task: run-integration-tests
    privileged: true
    config:
      image_resource:
        source:
          repository: simspace/ac-concourse-dind
          tag: 0.0.2
          username: ((concourse-dockerhub.username))
          password: ((concourse-dockerhub.password))
        type: registry-image
      platform: linux
      inputs:
      - name: liberator-repo
      - name: python-base-image
      - name: ac-loguru-repo
      run:
        path: entrypoint.sh
        args:
        - bash
        - -ceux
        - |
          eval $(ssh-agent)
          docker load < python-base-image/image.tar
          cd liberator-repo
          mkdir deps
          cp -R ../ac-loguru-repo deps/ac_loguru-v2.1.2
          rm -rf deps/ac_loguru-v2.1.2/.git
          make build-liberator
          make build-tests
          make run-unit-tests
