resources:
- name: concourse-test-repo
  type: git
  icon: github
  source:
    private_key: ((concourse-github.private_key))
    uri: git@github.com:jbourque-ss/concourse-test.git
    branch: main

jobs:
- name: build-concourse-test
  public: true
  plan:

  - get: concourse-test-repo

  - task: build-concourse-test-a
    config:
      image_resource:
        name: ""
        source:
          repository: concourse/oci-build-task
        type: registry-image
      inputs:
      - name: concourse-test-repo
      outputs:
      - name: image
      - name: all-images
      params:
        UNPACK_ROOTFS: true
        CONTEXT: concourse-test-repo
        DOCKERFILE: concourse-test-repo/ComponentA/Dockerfile
      platform: linux
      run:
        path: sh
        args:
          - -c
          - build && cp image/image.tar all-images/concourse-test-a.tar
    privileged: true
  
  - task: build-concourse-test-b
    config:
      image_resource:
        name: ""
        source:
          repository: concourse/oci-build-task
        type: registry-image
      inputs:
      - name: concourse-test-repo
      outputs:
      - name: image
      - name: all-images
      params:
        UNPACK_ROOTFS: true
        CONTEXT: concourse-test-repo
        DOCKERFILE: concourse-test-repo/ComponentB/Dockerfile
      platform: linux
      run:
        path: sh
        args:
          - -c
          - build && cp image/image.tar all-images/concourse-test-b.tar
    privileged: true
